### PR TITLE
beginning to implement george-appel algorithm [WIP]

### PR DESCRIPTION
**Pull request by jonsterling**
Just opening this pull request against our own fork, so that I can track the implementation work, solicit comments, etc. Very WIP.

### CODE REVIEW

**Comment by jonsterling** [comment]
@tanyongkiam Can you explain what `unspill` does, and what the `k` parameter of  `do_simplify` and similar functions is for?

**Comment by jonsterling** [comment]
@tanyongkiam Ah, I am guessing `k` is the number of registers available...

**Comment by tanyongkiam** [comment]
yes you're right for k.
unspill removes things that were originally in the spill worklist (with degree >= k) if they now have degree < k.
This could happen after you delete a node from the graph, for example.

**Comment by jonsterling** [comment]
@tanyongkiam I've add a bunch more of the algorithm from the George-Appel paper. The problem is that for some reason, I am now completely unable to build CakeML on my laptop (it's that same issue we discussed before), so I actually have no idea if this code even typechecks or is syntactically wellformed.

I can typecheck it when I get to my office... There are still some holes in here, and I suspect that we need to update existing parts of the algorithm.

A lot of the code is also fairly naive; for instance, I added all these lists about moves from the paper, and rather than checking membership in them repeatedly, we should be storing some kind of tag somewhere that says what list a node is in (and we'd have to keep this in sync).

**Pull request closed without merging**
